name: Common Workflow

on:
  workflow_call:
    inputs:
      deno-version:
        required: false
        type: string
        default: 'v2.x'
    secrets: {}

jobs:
  common:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install Chrome/Deno deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxcomposite1 \
            libxrandr2 \
            libxdamage1 \
            libgbm-dev \
            libasound2 \
            libpangocairo-1.0-0 \
            libgtk-3-0 \
            libx11-xcb1 \
            dbus \
            unzip

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      #      - name: Setup Chrome
      #        id: setup-chrome
      #        uses: browser-actions/setup-chrome@v1
      #        with:
      #          chrome-version: stable

      - name: Install Playwright dependencies

        run: npx --yes playwright install chrome --with-deps

      - name: Run tests
        run: BROWSER_EXECUTABLE_PATH="$(which google-chrome)" deno test -A

      - name: Lint documentation
        run: deno doc --lint ./lib
