name: Common Workflow

on:
  workflow_call:
    inputs:
      deno-version:
        required: false
        type: string
        default: 'v2.x'
    secrets: {}

jobs:
  common:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-noble
      options: --user 1001

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install Deno deps
        run: sudo apt-get install unzip

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      #      - name: Setup Chrome
      #        id: setup-chrome
      #        uses: browser-actions/setup-chrome@v1
      #        with:
      #          chrome-version: stable

      - name: Install Playwright dependencies
        run: npx playwright install chrome --with-deps --yes

      - name: Run tests
        run: BROWSER_EXECUTABLE_PATH="$(which google-chrome)" deno test -A

      - name: Lint documentation
        run: deno doc --lint ./lib
