name: Common Workflow

on:
  workflow_call:
    inputs:
      deno-version:
        required: false
        type: string
        default: 'v2.x'
    secrets: {}

jobs:
  # based on https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile
  common:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8 # Configure default locale (important for chrome-headless-shell).
      PPTRUSER_UID: 10042 # UID of the non-root user 'pptruser'
      DBUS_SESSION_BUS_ADDRESS: 'autolaunch:'

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Install Chrome/Deno deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            fonts-ipafont-gothic \
            fonts-wqy-zenhei \
            fonts-thai-tlwg \
            fonts-khmeros \
            fonts-kacst \
            fonts-freefont-ttf \
            dbus \
            dbus-x11 \
            unzip

      - name: Add pptruser
        run: groupadd -r pptruser && useradd -u $PPTRUSER_UID -rm -g pptruser -G audio,video pptruser

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      #      - name: Setup Chrome
      #        id: setup-chrome
      #        uses: browser-actions/setup-chrome@v1
      #        with:
      #          chrome-version: stable

      - name: Install Playwright dependencies

        run: npx --yes playwright install chrome --with-deps

      - name: Run tests
        run: BROWSER_EXECUTABLE_PATH="$(which google-chrome)" deno test -A

      - name: Lint documentation
        run: deno doc --lint ./lib
