name: Common Workflow

on:
  workflow_call:
    inputs:
      deno-version:
        required: false
        type: string
        default: 'v2.x'
    secrets: {}

jobs:
  common:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

#      - name: Setup Chrome
#        id: setup-chrome
#        uses: browser-actions/setup-chrome@v1
#        with:
#          chrome-version: stable
      - name: Install Playwright Browsers
        run: npx playwright install chrome --with-deps


      - name: Run tests
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
          export BROWSER_EXECUTABLE_PATH="$(which google-chrome)"
          sudo apt-get update && sudo apt-get install -y upower
          dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
          xvfb-run -a deno test -A

      - name: Lint documentation
        run: deno doc --lint ./lib

