name: Common Workflow

on:
  workflow_call:
    inputs:
      deno-version:
        required: false
        type: string
        default: 'v2.x'
    secrets: {}

jobs:
  common:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: -i --init --cap-add=SYS_ADMIN --user root

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ inputs.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Setup dbus
        run: service dbus start

      - name: Run tests
        run: deno test -A

      - name: Lint documentation
        run: deno doc --lint ./lib

